### PR TITLE
Support new version in Chromedriver asset name

### PR DESCRIPTION
**Pull request by kevinsawicki**
Support new version in asset name starting in 1.7.0

Refs https://github.com/electron/electron/pull/8682

### CODE REVIEW

**Comment by kevinsawicki** [comment]
> I assume this needs to be backported?

Do you mean to electron-download@1.3.x line?

**Comment by malept** [comment]
> > I assume this needs to be backported?
>
> Do you mean to electron-download 3.x line?

Yeah, I meant to the version that electron-prebuilt uses.

**Comment by kevinsawicki** [comment]
> Yeah, I meant to the version that electron-prebuilt uses.

I could definitely do that, although this won't impact `prebuilt` since it does not download Chromedriver, the only consumer of the chromedriver download path that I know of is https://github.com/electron/chromedriver which I was already going to upgrade to 4.x

**Comment by malept** [comment]
Ah, OK.  Sounds like that's not necessary, then.

**Pull request merged**
