### PR TITLE
Auto switch mirror for Great Firewall (of China)

### PR DESCRIPTION
**Pull request by gucong3000**

### CODE REVIEW

**Comment by fritx** [comment]
`async function` was used at https://github.com/gucong3000/in-gfw/blob/dc6796f2f9814414a6a955fa1a7734a5c5d29c26/lib/os.js#L4

which would require `node >= 7.6`
https://www.infoq.com/news/2017/02/node-76-async-await

and break compatibility defined at https://github.com/electron-userland/electron-download/blob/777ca9ff99906ba114e9a1d66717b3d904766cd1/package.json#L60-L62

```json
"engines": {
  "node": ">= 4.0"
}
```

**Comment by gucong3000** [comment]
Node V4 working properly:
https://travis-ci.org/electron-userland/electron-download/jobs/361947356

**Comment by gucong3000** [comment]
> async function was used

No, it is just a function named `async`

**Comment by MarshallOfSound** [comment]
This IMO is not something we want, we already have a well documented and well-used proxy / mirror logic that allows users to set this up themselves.  I don't want to point people somewhere else.

If you feel documentation around the mirror can be improved feel free but it is already referenced in the README of `electron/electron` so it can't get much more prominent.

**Comment by MarshallOfSound** [comment]
Woops, leaving open for discussion

**Comment by gucong3000** [comment]
> we already have a well documented and well-used

Most of the users that affected by Great Firewall speak Chinese. They can't read English.

**Comment by fritx** [comment]
> No, it is just a function named async

Haha... found myself stupid.. and `in-gfw` looks quite awesome.

**Pull request closed without merging**
